version: "3.5"
services:
  mysql:
    image: "mysql/mysql-server:5.7"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
  node:
    image: "node:14"
    depends_on:
      - mysql
    volumes:
      - ".:/app:ro"
networks:
  default:
    driver: overlay
